language: java
jdk:
    - oraclejdk8
script:
    - cd justify
    - mvn install
    - cd ../justify-cli
    - mvn package
    - cd target
    - tar xzf justify-cli-*.tar.gz
    - cd justify-cli
    - ./justify.sh examples/person.schema.json examples/person.json
